### ISSUE TITLE
Get rules 

### ISSUE THREAD

**Issue by alex1891** [sbezverk/nftableslib#56]
Hey there,
are their any plans to make an easy interface to get rules from a chain? At the moment I have to use the google/nftable lib and have to decode the expressions manually. And this is really a pain :) 

Greets from germany

Alex

**Comment by sbezverk** [comment]
Hello, thank you for interest in nftableslib. Could you be a bit more specific about your use case? There are a couple of things already, like `Dump()` call which gets a json like representation of all tables, chains and rules created by nftableslib's api calls. There is also `Sync()`, it loads from the host all tables, chains and rules which then can be `Dump()`ed. It is  experimental and I was planning to add it to e2e tests. If these 2 calls are not exactly what you need, then the explanation of your use case will help me to understand what you need and add it.
Best regards
Serguei

**Comment by alex1891** [comment]
Hi, thank you for the quick answer. What i want to do is to build a firewall web application basend on go. So I am not only need to set rules, I also have to get them to show data on the ui.

**Comment by sbezverk** [comment]
If you just want to visualize it, then `Dump()` could be sufficient. Check this out.
```
{"Name":"tf6341987","Use":0,"Flags":0,"Family":2}{"Name":"chain-1","Table":{"Name":"tf6341987","Use":0,"Flags":0,"Family":2},"Hooknum":4,"Priority":0,"Type":"nat","Policy":1}[{"DestRegister":1,"Base":"expr.PayloadBaseNetworkHeader","Len":1,"Offset":9},{"Op":"expr.CmpOpEq","Register":1,"Data":["0x11"]},{"Register":1,"Data":["0x5","0x5","0x5","0x5"]},{"Register":2,"Data":["0x1e","0x61"]},{"Type":0,"Family":2,"RegAddrMin":1,"RegAddrMax":0,"RegProtoMin":2,"RegProtoMax":0,"Random":"false","FullyRandom":"false","Persistent":"false"}
```

**Comment by sbezverk** [comment]
Closing as requested information was provided.

**Comment by sbezverk** [comment]
@greenpau currently You can dump rules of the specific chain using chain's Dump method. See: https://github.com/sbezverk/nftableslib/blob/master/nfchains.go#L61 It does not cover all type of Rules, I had other priorities, but it should be ok for basic ones. Here is example where Dump is used to convert into json all chains/rules for a specific table: https://github.com/sbezverk/nftableslib/blob/master/mock/mock_test.go#L623
Let me know if it works or not for your case.

**Comment by greenpau** [comment]
@sbezverk , thank you for a quick answer! 👍  Unfortunately, I would need to decode by hand. The `Dump()` does not give me much. I would need to spend time understanding the logic of rule construction, i.e. registers, etc.
